from .plan import plan_callback_handler
from .move_to_payment import move_to_payment_callback
from .payment_method import payment_method_callback
from .spb_payment import sbp_payment_callback
from .telegram_wallet_payment import telegram_wallet_payment_callback